language: objective-c
script:
  - xcodebuild test -project Fonty-Demo.xcodeproj -scheme 'Fonty-DemoTests' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -configuration Debug | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
